/** Command-palette grouping keys — shared contract between data and UI. */
export type PaletteGroup = "navigate" | "actions" | "theme" | "language";

export const en = {
  meta: {
    locale: "en",
    title: "James Maradiaga — Lead DevOps Engineer",
    description:
      "Lead DevOps Engineer in Guatemala. I design, automate and operate cloud infrastructure: Kubernetes, Terraform, CI/CD, observability and MLOps across AWS, Azure and GCP.",
    tagline: "Cloud infrastructure · SRE · MLOps",
  },

  nav: {
    sections: {
      home: "Home",
      about: "About",
      experience: "Experience",
      projects: "Projects",
      skills: "Skills",
      github: "GitHub",
      contact: "Contact",
    },
    menu: "Menu",
    close: "Close",
    skip: "Skip to content",
    palette: "Command menu",
    language: "Language",
    themeGroup: "Interface",
  },

  hero: {
    status: "Building infrastructure & automation",
    availability: "Open to interesting engineering problems",
    headline: "Building reliable infrastructure for software that matters.",
    sub: "Lead DevOps Engineer focused on cloud infrastructure, Kubernetes, automation, reliability, and AI/MLOps.",
    ctaPrimary: "View my work",
    ctaSecondary: "Get in touch",
    terminalTitle: "james@ops — zsh",
    terminalHint: "Replay",
    scroll: "Scroll",
    linkedin: "LinkedIn",
    github: "GitHub",
    email: "Email",
    photoAlt: "James Maradiaga",
    stats: {
      title: "Cluster",
      region: "gt-central-1",
      uptime: "status",
      healthy: "all systems steady",
    },
  },

  topology: {
    title: "delivery-pipeline",
    caption:
      "Illustrative diagram — the path a change takes from commit to production: pipeline, placement, runtime, observation.",
    legend: "Illustrative",
    stages: {
      source: "Source",
      pipeline: "Pipeline",
      iac: "Provision",
      cluster: "Cluster",
      cloud: "Cloud",
      apps: "Applications",
      observability: "Observability",
    },
    nodes: {
      developer: "Developer",
      git: "Git",
      actions: "GitHub Actions",
      terraform: "Terraform",
      kubernetes: "Kubernetes",
      docker: "Docker",
      aws: "AWS",
      azure: "Azure",
      gcp: "GCP",
      services: "Services",
      workers: "Workers",
      grafana: "Grafana",
      logs: "Logs",
      alerts: "Alerts",
    },
notes: {
      developer: "Where a change starts: a branch, a commit, a pull request.",
      git: "History nobody has to trust a memory for.",
      actions: "Every push runs the same checks in the same order, on the same runner image.",
      terraform: "The plan is reviewed as a diff before anything is applied.",
      aws: "Primary compute, networking and data services, provisioned from code.",
      azure: "Environments for teams already standardized on the Microsoft stack.",
      gcp: "GKE and data workloads, wired to the same conventions.",
      kubernetes: "Pods, quotas, policies and predictable node rotation.",
      docker: "One build artifact, promoted through environments unchanged.",
      services: "Long-running workloads with requests, limits and health checks.",
      workers: "Queues, scheduled jobs and the batch work that keeps latency flat.",
      grafana: "Dashboards that answer a question, not a wall of charts.",
      logs: "Structured, retained on purpose and searchable when it matters.",
      alerts: "Tied to symptoms users can feel, not to every CPU spike.",
    },
    inspect: "Inspect node",
    paused: "Paused",
    running: "Flowing",
  },

  about: {
    eyebrow: "01 — About",
    title: "I work on the layer below the product.",
    lead: "Most of my work happens where software meets the machine: Linux hosts, cloud accounts, container runtimes and the pipelines that move changes between them.",
    body: [
      "I build and operate platforms — the provisioning, the cluster, the delivery path, the dashboards someone opens at 03:00 when something is off. The goal is never tooling for its own sake: it is infrastructure that other engineers can reason about without needing me in the room.",
      "Day to day that means writing Terraform instead of clicking consoles, designing CI/CD that gives fast and honest feedback, hardening Kubernetes, and automating the operational work that would otherwise be done by hand at the wrong moment. I program in Python and Go, mostly to delete repetition.",
      "I work across Linux, cloud infrastructure, containers, Kubernetes, automation and programming. I care about the unglamorous parts: idempotency, least privilege, cost visibility, and knowing exactly what happens when a node disappears.",
    ],
    philosophyTitle: "Engineering philosophy",
    principles: {
      automate: {
        title: "Automate",
        body: "Reduce manual work and make systems reproducible. If a task needs to be done twice, it belongs in code.",
      },
      reliability: {
        title: "Engineer for reliability",
        body: "Design infrastructure that is observable, scalable and resilient — and assume the failure will happen during the worst possible change window.",
      },
      simple: {
        title: "Keep it simple",
        body: "Prefer understandable systems over unnecessary complexity. Boring infrastructure that everyone can read beats clever infrastructure only one person understands.",
      },
    },
    nowTitle: "Currently",
    now: [
      "Leading cloud infrastructure and DevOps practice at Niuro",
      "Kubernetes platforms, Infrastructure as Code and delivery pipelines",
      "Observability, security hardening and cost awareness",
      "Local AI infrastructure and production-oriented MLOps",
    ],
  },

  experience: {
    eyebrow: "02 — Experience",
    title: "A progression from support tickets to platform ownership.",
    lead: "Ten years ago I was fixing workstations. Today I lead the infrastructure other engineers ship on. The through-line is the same: understand the system, then remove the parts that hurt.",
    current: "Current",
    role: "Role",
    focus: "Focus",
    older: "Earlier",
    focusLabel: "Focus areas",
  },

  skills: {
    eyebrow: "04 — Skills",
    title: "Technology is only interesting in context.",
    lead: "Hover or focus any technology to see where it sits in the systems I build. Grouped by engineering domain, not by logo count.",
    hint: "Select a domain to filter",
    all: "All domains",
    searchLabel: "Filter technologies",
    searchPlaceholder: "filter…",
    empty: "No technology matches that filter.",
    count: "technologies",
    how: "How I use it",
  },

  projects: {
    eyebrow: "03 — Work",
    title: "Case studies, not screenshots.",
    lead: "These are the problem spaces I work in. Each one is written as an engineering case study — context, architecture and approach. Anything I cannot verify publicly is left out or marked accordingly.",
    open: "Read case study",
    close: "Close",
    soon: "Case study in progress",
    soonNote:
      "Written up as a working note rather than a marketing page. Detailed diagrams and outcomes are added once the write-up is reviewed.",
    diagramLabel: "Architecture",
    diagramNote: "Reference diagram of the shape of the system, simplified.",
    previous: "Previous",
    next: "Next",
    labels: {
      problem: "Problem",
      architecture: "Architecture",
      approach: "Approach",
      technology: "Technology",
      outcome: "Outcome",
      scope: "Scope",
    },
    caseStudyLabel: "Case study",
  },

  thinking: {
    eyebrow: "05 — Mental model",
    title: "How I think about infrastructure",
    lead: "These are not skills, they are constraints I design against. Each one changes the others — that tension is what makes infrastructure work.",
    focusHint: "Focus a principle to see how it changes the others",
    related: "Pulls on",
    detail: "What it changes",
  },

  github: {
    eyebrow: "06 — Open source",
    title: "Code, in public.",
    lead: "Pull live from the GitHub API at build time — no invented contribution numbers. Pinned repositories are real, unmodified projects.",
    profile: "Profile",
    viewProfile: "View GitHub profile",
    blog: "Technical blog",
    blogNote: "Writing about Linux, Kubernetes and automation.",
    repos: "Selected repositories",
    reposNote: "Sorted by last push. Descriptions as written by their author.",
    activity: "Contribution activity",
    activityNote: "Public contribution calendar for the last year.",
    contributions: "contributions in the last year",
    publicRepos: "public repositories",
    followers: "followers",
    following: "following",
    memberSince: "on GitHub since",
    pushed: "last push",
    pinned: "Pinned",
    liveNote: "Live data",
    stale: "Live data unavailable — showing the static fallback.",
    languages: "Primary languages",
  },

  contact: {
    eyebrow: "07 — Contact",
    title: "Have an infrastructure problem worth solving?",
    lead: "I'm interested in building reliable platforms, automating complex systems and solving difficult infrastructure problems.",
    email: "Email me",
    linkedin: "LinkedIn",
    github: "GitHub",
    copy: "Copy address",
    copied: "Copied",
    signature: "Built with Next.js, deployed like infrastructure.",
    interestTitle: "Things I'm happy to talk about",
    interests: [
      "Kubernetes platform design and operations",
      "Infrastructure as Code at team scale",
      "CI/CD that engineers actually trust",
      "Observability and incident response",
      "Cloud cost reduction without losing reliability",
      "MLOps and AI infrastructure",
    ],
  },

  palette: {
    title: "Command menu",
    placeholder: "Type a command or search…",
    empty: "No matching command.",
    groups: { navigate: "Navigate", actions: "Actions", theme: "Interface", language: "Language" } satisfies Record<PaletteGroup, string>,
    commands: {
      home: "Go to home",
      about: "Go to about",
      experience: "Go to experience",
      projects: "Go to projects",
      skills: "Go to skills",
      github: "Go to GitHub",
      contact: "Go to contact",
      email: "Copy email address",
      theme: "Switch to light interface",
      themeDark: "Switch to dark interface",
      langEs: "Cambiar a Español",
      langEn: "Switch to English",
      status: "Run status check",
      terminal: "Replay hero terminal",
      top: "Back to top",
    },
  },

  status: {
    title: "status",
    checking: "Checking endpoints…",
    endpoint: "Endpoint",
    region: "Region",
    allUp: "All endpoints answering",
    oneDown: "One endpoint unreachable",
    responseTime: "Response",
    footer: "Nothing here is a real production metric — it is a visual story.",
    ok200: "200 OK",
    offline: "offline",
  },

  egg: {
    hint: "Press ⌘K for the console",
    unlocked: "You found the console. Try: status, theme, lang, or g then a section key.",
    konami: "Pipeline burst — deploying straight to production.",
    terminalFound: "Hidden command found",
  },

  footer: {
    built: "Designed and built by James Maradiaga",
    stack: "Next.js · TypeScript · Tailwind",
    shortcuts: "Shortcuts",
    forAgents: "For agents",
    forAgentsIndex: "index",
    forAgentsMarkdown: "markdown",
    forAgentsSitemap: "urls",
    rights: "All rights reserved",
    version: "rev",
  },

  a11y: {
    external: "opens in a new tab",
    toggleMenu: "Toggle navigation",
    currentSection: "Current section",
  },
};

export type Dictionary = typeof en;
